### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by discoking** [CroweCybersecurity/echidna#1]
Is there a python version dependency? I am getting the following error using Ubuntu 16.04, with dependency libraries installed via pip. Python 2.7.12 both krbKeyGenerate.py and benchmark.py work fine.

:~/echidna$ python krbKeyCrack.py ../rockyou.txt TEST\test:aes128-cts-hmac-sha1-96:2e2028cb01c7192c57355df988b835a6
Traceback (most recent call last):
  File "krbKeyCrack.py", line 61, in <module>
    main(args.wordlist,args.key)
  File "krbKeyCrack.py", line 29, in main
    fin_salt = salt[0].upper() + salt[1]
IndexError: list index out of range

**Comment by ghost** [comment]
There are no dependency differences between the scripts.

This issue is caused by not escaping the backslash between the domain and username. Will need to modify your hash to TEST\\\\test.

**Comment by discoking** [comment]
Awsome!! Thanks for the quick response, that works.
